<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="4" tests="26" name="com.qa.centrum.eng.test.CentrumSampleAboutPage" time="300.097" errors="0" timestamp="2022-09-07T19:15:13 IST" skipped="8">
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="cookieButton" time="5.048"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="scienceLink" time="12.208"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumAdultsLink" time="28.695"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumMultiGummiesAdultsLink" time="17.719"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumMinis" time="16.301"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumMultigummiesWomen" time="15.324"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="verifyBuyNowOne" time="9.023">
    <skipped/>
  </testcase> <!-- verifyBuyNowOne -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="verifyBuyNowOne" time="7.834">
    <failure message="expected [about/] but found [products/multivitamins/centrum-adults/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [about/] but found [products/multivitamins/centrum-adults/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:708)
at com.qa.centrum.eng.test.CentrumSampleAboutPage.verifyBuyNowOne(CentrumSampleAboutPage.java:120)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyBuyNowOne -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="verifyBuyNowOne" time="26.918">
    <skipped/>
  </testcase> <!-- verifyBuyNowOne -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Compare1" time="9.908"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow2" time="8.372">
    <skipped/>
  </testcase> <!-- CentrumBuyNow2 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow2" time="12.644">
    <skipped/>
  </testcase> <!-- CentrumBuyNow2 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow2" time="10.160">
    <failure message="expected [about/] but found [products/multivitamins/centrum-multigummies-adults/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [about/] but found [products/multivitamins/centrum-multigummies-adults/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:708)
at com.qa.centrum.eng.test.CentrumSampleAboutPage.CentrumBuyNow2(CentrumSampleAboutPage.java:145)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CentrumBuyNow2 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Compare2" time="9.205"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow3" time="10.920">
    <failure message="expected [about/] but found [products/multivitamins/centrum-minis-adults-50-plus/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [about/] but found [products/multivitamins/centrum-minis-adults-50-plus/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:708)
at com.qa.centrum.eng.test.CentrumSampleAboutPage.CentrumBuyNow3(CentrumSampleAboutPage.java:172)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CentrumBuyNow3 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow3" time="8.132">
    <skipped/>
  </testcase> <!-- CentrumBuyNow3 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow3" time="9.604">
    <skipped/>
  </testcase> <!-- CentrumBuyNow3 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Compare3" time="9.803"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow4" time="11.184">
    <skipped/>
  </testcase> <!-- CentrumBuyNow4 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow4" time="8.062">
    <skipped/>
  </testcase> <!-- CentrumBuyNow4 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="CentrumBuyNow4" time="8.075">
    <failure message="expected [about/] but found [products/multivitamins/centrum-multigummies-women-50-plus/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [about/] but found [products/multivitamins/centrum-multigummies-women-50-plus/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:708)
at com.qa.centrum.eng.test.CentrumSampleAboutPage.CentrumBuyNow4(CentrumSampleAboutPage.java:197)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CentrumBuyNow4 -->
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Compare4" time="9.761"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Article1" time="8.144"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Article2" time="7.859"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Article3" time="10.364"/>
  <system-out/>
  <testcase classname="com.qa.centrum.eng.test.CentrumSampleAboutPage" name="Article4" time="8.830"/>
  <system-out/>
</testsuite> <!-- com.qa.centrum.eng.test.CentrumSampleAboutPage -->
